In [1]:
import pandas as pd
import os
from skimage.transform import resize
from skimage.io import imread
import numpy as np
import matplotlib.pyplot as plt
from tkinter import *
import tkinter
from sklearn.model_selection import train_test_split
from tkinter import filedialog
from sklearn import svm
from sklearn.metrics import accuracy_score
from tkinter import messagebox
from PIL import ImageTk, Image
from tkinter import filedialog, ttk
from sklearn.tree import DecisionTreeClassifier
import pickle
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, Flatten, MaxPooling2D
# from keras.utils import np_utils
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import load_model

In [2]:
Categories = ['benign', 'malignant', 'normal']
flat_data_arr = []  # khởi tạo input array
target_arr = []  # khởi tạo output array
datadir = 'D:\py\Đồ án TTNT\Dataset_BUSI_with_GT'

# load, xử lý dư liệu
for i in Categories:
    print(f'loading...  {i}...')
    path = os.path.join(datadir, i)
    for img in os.listdir(path):
        img_array = imread(os.path.join(path, img))
        img_resized = resize(img_array, (150, 150, 3))  # thay đổi kích thước ảnh
        flat_data_arr.append(img_resized.flatten())  # flatten làm phẳng bức ảnh đa chiều thành 1 chiều tạp ra 1 dãy dữ liệu
        target_arr.append(Categories.index(i))
    print(f'Done!!!')

flat_data = np.array(flat_data_arr)
target = np.array(target_arr)
df = pd.DataFrame(flat_data)  # dataframe
df['Target'] = target
x = df.iloc[:, :-1]  # input data lấy đến kế cuối
y = df.iloc[:, -1]  # output data là dòng cuối

<>:4: SyntaxWarning: invalid escape sequence '\p'
<>:4: SyntaxWarning: invalid escape sequence '\p'
C:\Users\PHONG\AppData\Local\Temp\ipykernel_29232\1910978820.py:4: SyntaxWarning: invalid escape sequence '\p'
  datadir = 'D:\py\Đồ án TTNT\Dataset_BUSI_with_GT'


loading...  benign...
Done!!!
loading...  malignant...
Done!!!
loading...  normal...
Done!!!


In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=20)
x_train = np.reshape(x_train, (-1, 150, 150, 3))
x_test = np.reshape(x_test, ( -1,150, 150, 3))
y_train = to_categorical(y_train, 3)
y_test = to_categorical(y_test, 3)
print(y_train)


[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [21]:
model2 = Sequential()
# convolutional layer
model2.add(Conv2D(16, (3, 3), activation='relu', input_shape=(x_train[0].shape)))
#model2.add(MaxPool2D(pool_size=(1,1)))
model2.add(MaxPooling2D((2, 2)))
model2.add(Conv2D(32, (3, 3), activation='relu'))
model2.add(MaxPooling2D((2, 2)))
model2.add(Conv2D(64, (3, 3), activation='relu'))
model2.add(MaxPooling2D((2, 2)))
model2.add(Dropout(0.2))
# flatten output of conv
model2.add(Flatten())
# hidden layer5
model2.add(Dense(128, activation='relu'))
# output layer
model2.add(Dense(3, activation='softmax'))

# compiling the sequential model
model2.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

# training the model for 10 epochs
model2.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 3s 59ms/step - accuracy: 0.4632 - loss: 0.9520 - val_accuracy: 0.6962 - val_loss: 0.7494
Epoch 2/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step - accuracy: 0.6970 - loss: 0.6868 - val_accuracy: 0.7342 - val_loss: 0.6166
Epoch 3/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step - accuracy: 0.7302 - loss: 0.5508 - val_accuracy: 0.7468 - val_loss: 0.6267
Epoch 4/10
40/40 ━━━━━━━━━━━━━━━━━━━━ 2s 57ms/step - accuracy: 0.7944 - loss: 0.4751 - val_accuracy: 0.7532 - val_loss: 0.5941
Epoch 5/10
22/40 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.8350 - loss: 0.3937

KeyboardInterrupt: 